from .resource import ResourceNoneInteraction,TestResourceInteraction, TestResourceNoneInteraction


testResourceInteraction = TestResourceInteraction()
testResourceNoneInteraction = TestResourceNoneInteraction()